title: Gurteg Singh
email: gurtegsingh2999@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Gurteg Singh's Personal Website and Portfolio
baseurl: "" # the subpath of your site, e.g. /blog
url: "gurtegsingh2999.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  gus474

# Build settings
highlighter: rouge
markdown: kramdown
# theme: minimal-mistakes-jekyll
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
include: ["_pages"]
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true 
      read_time: true
      comments: false
      share: true
      related: false
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
